/*
 * Copyright 2014 Hieu Rocker
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.white.usee.app.util.emojicon.emoji;

/**
 * @author Hieu Rocker (rockerhieu@gmail.com)
 */
public class Nature {
    public static final Emojicon[] DATA = new Emojicon[]{
            Emojicon.fromChars("/1f436]"),
            Emojicon.fromChars("/1f43a]"),
            Emojicon.fromChars("/1f431]"),
            Emojicon.fromChars("/1f42d]"),
            Emojicon.fromChars("/1f439]"),
            Emojicon.fromChars("/1f430]"),
            Emojicon.fromChars("/1f438]"),
            Emojicon.fromChars("/1f42f]"),
            Emojicon.fromChars("/1f428]"),
            Emojicon.fromChars("/1f43b]"),
            Emojicon.fromChars("/1f437]"),
            Emojicon.fromChars("/1f43d]"),
            Emojicon.fromChars("/1f42e]"),
            Emojicon.fromChars("/1f417]"),
            Emojicon.fromChars("/1f435]"),
            Emojicon.fromChars("/1f412]"),
            Emojicon.fromChars("/1f434]"),
            Emojicon.fromChars("/1f411]"),
            Emojicon.fromChars("/1f418]"),
            Emojicon.fromChars("/1f43c]"),
            Emojicon.fromChars("/1f427]"),
            Emojicon.fromChars("/1f426]"),
            Emojicon.fromChars("/1f424]"),
            Emojicon.fromChars("/1f425]"),
            Emojicon.fromChars("/1f423]"),
            Emojicon.fromChars("/1f414]"),
            Emojicon.fromChars("/1f40d]"),
            Emojicon.fromChars("/1f422]"),
            Emojicon.fromChars("/1f41b]"),
            Emojicon.fromChars("/1f41d]"),
            Emojicon.fromChars("/1f41c]"),
            Emojicon.fromChars("/1f41e]"),
            Emojicon.fromChars("/1f40c]"),
            Emojicon.fromChars("/1f419]"),
            Emojicon.fromChars("/1f41a]"),
            Emojicon.fromChars("/1f420]"),
            Emojicon.fromChars("/1f41f]"),
            Emojicon.fromChars("/1f42c]"),
            Emojicon.fromChars("/1f433]"),
            Emojicon.fromChars("/1f40b]"),
            Emojicon.fromChars("/1f404]"),
            Emojicon.fromChars("/1f40f]"),
            Emojicon.fromChars("/1f400]"),
            Emojicon.fromChars("/1f403]"),
            Emojicon.fromChars("/1f405]"),
            Emojicon.fromChars("/1f407]"),
            Emojicon.fromChars("/1f409]"),
            Emojicon.fromChars("/1f40e]"),
            Emojicon.fromChars("/1f410]"),
            Emojicon.fromChars("/1f413]"),
            Emojicon.fromChars("/1f415]"),
            Emojicon.fromChars("/1f416]"),
            Emojicon.fromChars("/1f401]"),
            Emojicon.fromChars("/1f402]"),
            Emojicon.fromChars("/1f432]"),
            Emojicon.fromChars("/1f421]"),
            Emojicon.fromChars("/1f40a]"),
            Emojicon.fromChars("/1f42b]"),
            Emojicon.fromChars("/1f42a]"),
            Emojicon.fromChars("/1f406]"),
            Emojicon.fromChars("/1f408]"),
            Emojicon.fromChars("/1f429]"),
            Emojicon.fromChars("/1f43e]"),
            Emojicon.fromChars("/1f490]"),
            Emojicon.fromChars("/1f338]"),
            Emojicon.fromChars("/1f337]"),
            Emojicon.fromChars("/1f340]"),
            Emojicon.fromChars("/1f339]"),
            Emojicon.fromChars("/1f33b]"),
            Emojicon.fromChars("/1f33a]"),
            Emojicon.fromChars("/1f341]"),
            Emojicon.fromChars("/1f343]"),
            Emojicon.fromChars("/1f342]"),
            Emojicon.fromChars("/1f33f]"),
            Emojicon.fromChars("/1f33e]"),
            Emojicon.fromChars("/1f344]"),
            Emojicon.fromChars("/1f335]"),
            Emojicon.fromChars("/1f334]"),
            Emojicon.fromChars("/1f332]"),
            Emojicon.fromChars("/1f333]"),
            Emojicon.fromChars("/1f330]"),
            Emojicon.fromChars("/1f331]"),
            Emojicon.fromChars("/1f33c]"),
            Emojicon.fromChars("/1f310]"),
            Emojicon.fromChars("/1f31e]"),
            Emojicon.fromChars("/1f31d]"),
            Emojicon.fromChars("/1f31a]"),
            Emojicon.fromChars("/1f311]"),
            Emojicon.fromChars("/1f312]"),
            Emojicon.fromChars("/1f313]"),
            Emojicon.fromChars("/1f314]"),
            Emojicon.fromChars("/1f315]"),
            Emojicon.fromChars("/1f316]"),
            Emojicon.fromChars("/1f317]"),
            Emojicon.fromChars("/1f318]"),
            Emojicon.fromChars("/1f31c]"),
            Emojicon.fromChars("/1f31b]"),
            Emojicon.fromChars("/1f319]"),
            Emojicon.fromChars("/1f30d]"),
            Emojicon.fromChars("/1f30e]"),
            Emojicon.fromChars("/1f30f]"),
            Emojicon.fromChars("/1f30b]"),
            Emojicon.fromChars("/1f30c]"),
            Emojicon.fromChars("/1f320]"),
            Emojicon.fromChars("/2b50]"),
            Emojicon.fromChars("/2600]"),
            Emojicon.fromChars("/26c5]"),
            Emojicon.fromChars("/2601]"),
            Emojicon.fromChars("/26a1]"),
            Emojicon.fromChars("/2614]"),
            Emojicon.fromChars("/2744]"),
            Emojicon.fromChars("/26c4]"),
            Emojicon.fromChars("/1f300]"),
            Emojicon.fromChars("/1f301]"),
            Emojicon.fromChars("/1f308]"),
            Emojicon.fromChars("/1f30a]"),
    };
}
