/*
 * Copyright 2014 Hieu Rocker
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.white.usee.app.util.emojicon.emoji;

/**
 * @author Hieu Rocker (rockerhieu@gmail.com)
 */
public class Places {
    public static final Emojicon[] DATA = new Emojicon[]{
            Emojicon.fromChars("/1f3e0]"),
            Emojicon.fromChars("/1f3e1]"),
            Emojicon.fromChars("/1f3eb]"),
            Emojicon.fromChars("/1f3e2]"),
            Emojicon.fromChars("/1f3e3]"),
            Emojicon.fromChars("/1f3e5]"),
            Emojicon.fromChars("/1f3e6]"),
            Emojicon.fromChars("/1f3ea]"),
            Emojicon.fromChars("/1f3e9]"),
            Emojicon.fromChars("/1f3e8]"),
            Emojicon.fromChars("/1f492]"),
            Emojicon.fromChars("/26ea]"),
            Emojicon.fromChars("/1f3ec]"),
            Emojicon.fromChars("/1f3e4]"),
            Emojicon.fromChars("/1f307]"),
            Emojicon.fromChars("/1f306]"),
            Emojicon.fromChars("/1f3ef]"),
            Emojicon.fromChars("/1f3f0]"),
            Emojicon.fromChars( "/26fa]"),
            Emojicon.fromChars("/1f3ed]"),
            Emojicon.fromChars("/1f5fc]"),
            Emojicon.fromChars("/1f5fe]"),
            Emojicon.fromChars("/1f5fb]"),
            Emojicon.fromChars("/1f304]"),
            Emojicon.fromChars("/1f305]"),
            Emojicon.fromChars("/1f303]"),
            Emojicon.fromChars("/1f5fd]"),
            Emojicon.fromChars("/1f309]"),
            Emojicon.fromChars("/1f3a0]"),
            Emojicon.fromChars("/1f3a1]"),
            Emojicon.fromChars( "/26f2]"),
            Emojicon.fromChars("/1f3a2]"),
            Emojicon.fromChars("/1f6a2]"),
            Emojicon.fromChars( "/26f5]"),
            Emojicon.fromChars("/1f6a4]"),
            Emojicon.fromChars("/1f6a3]"),
            Emojicon.fromChars( "/2693]"),
            Emojicon.fromChars("/1f680]"),
            Emojicon.fromChars( "/2708]"),
            Emojicon.fromChars("/1f4ba]"),
            Emojicon.fromChars("/1f681]"),
            Emojicon.fromChars("/1f682]"),
            Emojicon.fromChars("/1f68a]"),
            Emojicon.fromChars("/1f689]"),
            Emojicon.fromChars("/1f69e]"),
            Emojicon.fromChars("/1f686]"),
            Emojicon.fromChars("/1f684]"),
            Emojicon.fromChars("/1f685]"),
            Emojicon.fromChars("/1f688]"),
            Emojicon.fromChars("/1f687]"),
            Emojicon.fromChars("/1f69d]"),
            Emojicon.fromChars("/1f68b]"),
            Emojicon.fromChars("/1f683]"),
            Emojicon.fromChars("/1f68e]"),
            Emojicon.fromChars("/1f68c]"),
            Emojicon.fromChars("/1f68d]"),
            Emojicon.fromChars("/1f699]"),
            Emojicon.fromChars("/1f698]"),
            Emojicon.fromChars("/1f697]"),
            Emojicon.fromChars("/1f695]"),
            Emojicon.fromChars("/1f696]"),
            Emojicon.fromChars("/1f69b]"),
            Emojicon.fromChars("/1f69a]"),
            Emojicon.fromChars("/1f6a8]"),
            Emojicon.fromChars("/1f693]"),
            Emojicon.fromChars("/1f694]"),
            Emojicon.fromChars("/1f692]"),
            Emojicon.fromChars("/1f691]"),
            Emojicon.fromChars("/1f690]"),
            Emojicon.fromChars("/1f6b2]"),
            Emojicon.fromChars("/1f6a1]"),
            Emojicon.fromChars("/1f69f]"),
            Emojicon.fromChars("/1f6a0]"),
            Emojicon.fromChars("/1f69c]"),
            Emojicon.fromChars("/1f488]"),
            Emojicon.fromChars("/1f68f]"),
            Emojicon.fromChars("/1f3ab]"),
            Emojicon.fromChars("/1f6a6]"),
            Emojicon.fromChars("/1f6a5]"),
            Emojicon.fromChars( "/26a0]"),
            Emojicon.fromChars("/1f6a7]"),
            Emojicon.fromChars("/1f530]"),
            Emojicon.fromChars( "/26fd]"),
            Emojicon.fromChars("/1f3ee]"),
            Emojicon.fromChars("/1f3b0]"),
            Emojicon.fromChars( "/2668]"),
            Emojicon.fromChars("/1f5ff]"),
            Emojicon.fromChars("/1f3aa]"),
            Emojicon.fromChars("/1f3ad]"),
            Emojicon.fromChars("/1f4cd]"),
            Emojicon.fromChars("/1f6a9]"),
            Emojicon.fromChars("\ud83c\uddef\ud83c\uddf5"),
            Emojicon.fromChars("\ud83c\uddf0\ud83c\uddf7"),
            Emojicon.fromChars("\ud83c\udde9\ud83c\uddea"),
            Emojicon.fromChars("\ud83c\udde8\ud83c\uddf3"),
            Emojicon.fromChars("\ud83c\uddfa\ud83c\uddf8"),
            Emojicon.fromChars("\ud83c\uddeb\ud83c\uddf7"),
            Emojicon.fromChars("\ud83c\uddea\ud83c\uddf8"),
            Emojicon.fromChars("\ud83c\uddee\ud83c\uddf9"),
            Emojicon.fromChars("\ud83c\uddf7\ud83c\uddfa"),
            Emojicon.fromChars("\ud83c\uddec\ud83c\udde7"),
    };
}
